development:
  adapter: "pdo_sqlite"
  database: "db/database.sqlite3"

test:
  adapter: "pdo_sqlite"
  database: "db/database.sqlite3"

production:
  adapter: "pdo_sqlite"
  database: "db/database.sqlite3"
