#!/usr/bin/env php
<?php

define('MAD_ENV', isset($_SERVER['MAD_ENV']) ? $_SERVER['MAD_ENV'] : 'development');

echo "Loading ".MAD_ENV." environment\n";

putenv('MAD_ENV=' . MAD_ENV);
pcntl_exec(PHP_BINARY, [
    '-d', 'auto_prepend_file=' . dirname(__DIR__) . '/config/environment.php',
    '-a'
]);
