#!/usr/bin/env php
<?php

// check for environement arg
foreach ($argv as $key => $value) {
    if (preg_match('/MAD_ENV=(.*)/', $value, $match)) {
        define('MAD_ENV', strtolower($match[1]));
        unset($argv[$key]);
        $argv = array_values($argv);
    }
}

/**
 * Set environment
 */
if (!defined('MAD_ENV')) {
    if (isset($_SERVER['MAD_ENV'])) {
        $env = $_SERVER['MAD_ENV'];
    } elseif (isset($argv[1]) && strncmp($argv[1], 'test', 4) === 0) {
        $env = 'test';
    } else {
        $env = 'development';
    }
    define('MAD_ENV', $env);
}
require_once dirname(dirname(__FILE__)).'/config/environment.php';

new Mad_Script_TaskRunner($argv);
